name: Lint on Push and Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] # Remplacer 'main' par votre branche principale

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit checks
        run: |
          pre-commit install
          pre-commit autoupdate
          pre-commit run --all
